FROM maven:3.6-jdk-11 AS build
WORKDIR /usr/src/myapp
COPY src ./src
COPY pom.xml .
RUN mvn package

FROM tomcat:9.0.76-jdk11-temurin-focal
COPY --from=build /usr/src/myapp/target/java-static-site.war /usr/local/tomcat/webapps/ROOT.war
WORKDIR /usr/local/tomcat/bin/
ENTRYPOINT ["catalina.sh", "run"]